In [ ]:
pip install quandl

In [1]:
import quandl
import pandas as pd
import numpy as np



quandl.ApiConfig.api_key = 'PRemcPEEZsHua9eMcurU'

In [2]:
AZips = pd.read_excel('../data/Atlanta_Metro_Zips.xlsx')

In [3]:
AZips

     Zip Code         City    County
0       30004   Alpharetta    Fulton
1       30005   Alpharetta    Fulton
2       30009   Alpharetta    Fulton
3       30022   Alpharetta    Fulton
4       30075      Roswell    Fulton
..        ...          ...       ...
130     30253    Mcdonough     Henry
131     30281  Stockbridge     Henry
132     30012      Conyers  Rockdale
133     30013      Conyers  Rockdale
134     30094      Conyers  Rockdale

[135 rows x 3 columns]

In [4]:
InputCodes = pd.read_csv('../data/clean_zillow_codes.csv', header=0)
InputCodes

        Code                                               Name
0   _FOR10KM                  Foreclosures Per 10,000 Homes MSA
1     _MLPAH                   Median Listing Price - All Homes
2    _MLPFAH   Median Listing Price Per Square Foot - All Homes
3     _MRPAH                    Median Rental Price - All Homes
4    _MRPFAH    Median Rental Price Per Square Foot - All Homes
5     _MSPAH                      Median Sold Price - All Homes
6   _MVALFAH           Median Value Per Square Foot - All Homes
7       _NFS                                           NF Sales
8   _NMLNSAH             New Monthly Listings - NSA - All Homes
9   _NMLSAAH              New Monthly Listings - SA - All Homes
10   _PHDVAH  Percent Of Homes Decreasing In Values - All Homes
11   _PHIVAH  Percent Of Homes Increasing In Values - All Homes
12   _PLPRAH  Percent Of Listings With Price Reductions - Al...
13    _PRRAH                    Price To Rent Ratio - All Homes
14   _TURNAH                               Turnover - All Homes
15    _USRAH                           Unsold Renos - All Homes
16   _ZHVIAH                Zillow Home Value Index - All Homes
17    _ZRIAH                    Zillow Rental Index - All Homes

In [5]:
Codes=InputCodes["Code"]
Category=InputCodes["Name"]

In [ ]:
# Median Listing Price
# ONLY RUN WHEN LOOKING AT LISTING PRICE INFO
Codes=["_MLPAH",
       "_MLPFAH",
       "_MRPAH",
       "_MRPFAH"
]

In [ ]:
# Category Descriptors
Category=["Median Listing Price - All Homes",
          "Median Listing Price Per Square Foot - All Homes",
          "Median Rental Price - All Homes",
          "Median Rental Price Per Square Foot - All Homes"
]

In [7]:
#TEST ONLY

ZC="30004"

for item in Codes:
    this_code="ZILLOW/Z"+ZC+item
    #temp = quandl.get(this_code)
    #final = temp['Value'].size
    #test = temp.Value[temp['Value'].size-1]
    #test
    print(this_code)

ZILLOW/Z30004_FOR10KM
ZILLOW/Z30004_MLPAH
ZILLOW/Z30004_MLPFAH
ZILLOW/Z30004_MRPAH
ZILLOW/Z30004_MRPFAH
ZILLOW/Z30004_MSPAH
ZILLOW/Z30004_MVALFAH
ZILLOW/Z30004_NFS
ZILLOW/Z30004_NMLNSAH
ZILLOW/Z30004_NMLSAAH
ZILLOW/Z30004_PHDVAH
ZILLOW/Z30004_PHIVAH
ZILLOW/Z30004_PLPRAH
ZILLOW/Z30004_PRRAH
ZILLOW/Z30004_TURNAH
ZILLOW/Z30004_USRAH
ZILLOW/Z30004_ZHVIAH
ZILLOW/Z30004_ZRIAH

In [6]:
ZipList=AZips["Zip Code"]
ZipList

0      30004
1      30005
2      30009
3      30022
4      30075
       ...
130    30253
131    30281
132    30012
133    30013
134    30094
Name: Zip Code, Length: 135, dtype: int64

In [25]:
# Median Listing Price
# ONLY RUN WHEN LOOKING AT LISTING PRICE INFO
Codes=["_MLPAH"
]

In [ ]:
temp_csv =

In [13]:
#ZipList=["30004","30005","30009"...]

df=pd.DataFrame()

for ZC in ZipList:
    #loop through and pull the last line from each API Call
    # ******* Does the API Calls
    stats=[]
    for item in Codes:
        this_code="ZILLOW/Z"+str(ZC)+item
        try:
            temp = quandl.get(this_code)
            final = temp['Value'].size
            test = temp.Value[temp['Value'].size-1]
        except:
            test = np.nan
        stats.append(test)
        #print(this_code)
    df[ZC]=stats

In [14]:
df

,30004,30005,30009,30022,30075,30076,30097,30213,30268,30291,...,30296,30297,30228,30248,30252,30253,30281,30012,30013,30094
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,540000.000000,489000.000000,556100.500000,449900.000000,515000.000000,410000.000000,475000.000000,228380.000000,277450.000000,150990.000000,...,159900.000000,100000.000000,207900.000000,235900.000000,293945.000000,216499.500000,218900.000000,175950.000000,239900.000000,216500.000000
2,175.844051,176.872670,215.593750,166.361225,184.085815,166.797591,151.234803,93.589419,121.951220,81.021576,...,106.703881,96.913580,104.415137,100.255540,105.732527,98.331884,98.763889,95.213709,97.914400,99.132052
3,1900.000000,2245.000000,2000.000000,1950.000000,2185.000000,1887.500000,2000.000000,1545.000000,NaN,1275.000000,...,1212.500000,985.000000,1385.000000,1447.000000,1495.000000,1449.000000,1340.000000,1210.000000,1195.000000,1365.000000
4,0.946454,0.925988,1.163829,0.962082,1.022222,1.043742,0.840823,0.794118,NaN,0.760026,...,1.010937,0.952282,0.952550,0.735976,0.819980,0.794764,0.802055,0.754916,0.769231,0.838983
5,323130.000000,406320.000000,299725.000000,368650.000000,367050.000000,303975.000000,331100.000000,164625.000000,148846.153800,73575.000000,...,88765.000000,47050.000000,156715.000000,148895.000000,196985.000000,163550.000000,145150.000000,78500.000000,137462.500000,161050.000000
6,491.000000,496.000000,423.000000,400.000000,354.000000,276.000000,145.000000,188.000000,299.000000,22.000000,...,281.000000,167.000000,168.000000,99.000000,112.000000,135.000000,129.000000,233.000000,182.000000,250.000000
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,125.000000,56.000000,63.000000,78.000000,116.000000,65.000000,74.000000,56.000000,14.000000,23.000000,...,29.000000,12.000000,57.000000,58.000000,103.000000,87.000000,76.000000,49.000000,28.000000,34.000000
9,95.000000,41.000000,51.000000,65.000000,82.000000,57.000000,67.000000,52.000000,19.000000,31.000000,...,28.000000,17.000000,51.000000,55.000000,92.000000,93.000000,70.000000,40.000000,30.000000,42.000000
10,45.090000,27.840000,28.480000,27.120000,36.930000,18.650000,54.880000,18.240000,18.240000,8.720000,...,9.320000,3.570000,32.260000,26.150000,25.000000,23.660000,17.210000,7.820000,16.320000,13.130000
11,54.160000,71.680000,71.110000,72.490000,62.580000,81.000000,44.610000,81.030000,81.500000,90.880000,...,90.380000,96.310000,66.840000,72.940000,74.220000,75.790000,82.390000,92.040000,83.300000,86.730000
12,13.210702,13.438735,11.983471,13.238771,16.263736,17.747440,10.582011,10.850440,8.163265,8.720930,...,7.692308,10.112360,9.052632,9.840426,13.592233,9.009009,9.382716,12.307692,11.881188,13.090909
13,16.000000,27.520000,32.660000,34.580000,27.480000,44.090000,11.830000,18.400000,23.430000,19.520000,...,18.850000,26.970000,14.930000,16.850000,18.660000,21.200000,26.490000,76.150000,54.770000,61.350000
14,4.077000,5.062900,5.065100,3.962000,4.531400,5.397300,4.595300,1.073300,2.964000,0.262800,...,2.658300,3.142800,5.225400,6.786300,6.443500,5.318400,4.458700,4.007000,5.609500,4.575400
15,30.300000,27.000000,58.200000,35.200000,37.400000,34.300000,13.200000,300.500000,66.300000,196.600000,...,107.900000,128.100000,166.400000,108.300000,86.100000,107.800000,90.300000,92.600000,85.300000,67.400000
16,463781.000000,468553.000000,413467.000000,437304.000000,450374.000000,383102.000000,462955.000000,203130.000000,189892.000000,151501.000000,...,152112.000000,87927.000000,194178.000000,200900.000000,246812.000000,204702.000000,186181.000000,154284.000000,198094.000000,200362.000000
17,2225.000000,2392.000000,2148.000000,2273.000000,2274.000000,2037.000000,2340.000000,1528.000000,1421.000000,1315.000000,...,1210.000000,958.000000,1401.000000,1433.000000,1577.000000,1494.000000,1386.000000,1251.000000,1384.000000,1397.000000

In [15]:
df2=df
df2['Titles']=Category
df2.set_index('Titles',inplace=True)
df2

,30004,30005,30009,30022,30075,30076,30097,30213,30268,30291,...,30296,30297,30228,30248,30252,30253,30281,30012,30013,30094
Titles,,,,,,,,,,,,,,,,,,,,,
"Foreclosures Per 10,000 Homes MSA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Median Listing Price - All Homes,540000.000000,489000.000000,556100.500000,449900.000000,515000.000000,410000.000000,475000.000000,228380.000000,277450.000000,150990.000000,...,159900.000000,100000.000000,207900.000000,235900.000000,293945.000000,216499.500000,218900.000000,175950.000000,239900.000000,216500.000000
Median Listing Price Per Square Foot - All Homes,175.844051,176.872670,215.593750,166.361225,184.085815,166.797591,151.234803,93.589419,121.951220,81.021576,...,106.703881,96.913580,104.415137,100.255540,105.732527,98.331884,98.763889,95.213709,97.914400,99.132052
Median Rental Price - All Homes,1900.000000,2245.000000,2000.000000,1950.000000,2185.000000,1887.500000,2000.000000,1545.000000,NaN,1275.000000,...,1212.500000,985.000000,1385.000000,1447.000000,1495.000000,1449.000000,1340.000000,1210.000000,1195.000000,1365.000000
Median Rental Price Per Square Foot - All Homes,0.946454,0.925988,1.163829,0.962082,1.022222,1.043742,0.840823,0.794118,NaN,0.760026,...,1.010937,0.952282,0.952550,0.735976,0.819980,0.794764,0.802055,0.754916,0.769231,0.838983
Median Sold Price - All Homes,323130.000000,406320.000000,299725.000000,368650.000000,367050.000000,303975.000000,331100.000000,164625.000000,148846.153800,73575.000000,...,88765.000000,47050.000000,156715.000000,148895.000000,196985.000000,163550.000000,145150.000000,78500.000000,137462.500000,161050.000000
Median Value Per Square Foot - All Homes,491.000000,496.000000,423.000000,400.000000,354.000000,276.000000,145.000000,188.000000,299.000000,22.000000,...,281.000000,167.000000,168.000000,99.000000,112.000000,135.000000,129.000000,233.000000,182.000000,250.000000
NF Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New Monthly Listings - NSA - All Homes,125.000000,56.000000,63.000000,78.000000,116.000000,65.000000,74.000000,56.000000,14.000000,23.000000,...,29.000000,12.000000,57.000000,58.000000,103.000000,87.000000,76.000000,49.000000,28.000000,34.000000
New Monthly Listings - SA - All Homes,95.000000,41.000000,51.000000,65.000000,82.000000,57.000000,67.000000,52.000000,19.000000,31.000000,...,28.000000,17.000000,51.000000,55.000000,92.000000,93.000000,70.000000,40.000000,30.000000,42.000000
Percent Of Homes Decreasing In Values - All Homes,45.090000,27.840000,28.480000,27.120000,36.930000,18.650000,54.880000,18.240000,18.240000,8.720000,...,9.320000,3.570000,32.260000,26.150000,25.000000,23.660000,17.210000,7.820000,16.320000,13.130000
Percent Of Homes Increasing In Values - All Homes,54.160000,71.680000,71.110000,72.490000,62.580000,81.000000,44.610000,81.030000,81.500000,90.880000,...,90.380000,96.310000,66.840000,72.940000,74.220000,75.790000,82.390000,92.040000,83.300000,86.730000
Percent Of Listings With Price Reductions - All Homes,13.210702,13.438735,11.983471,13.238771,16.263736,17.747440,10.582011,10.850440,8.163265,8.720930,...,7.692308,10.112360,9.052632,9.840426,13.592233,9.009009,9.382716,12.307692,11.881188,13.090909
Price To Rent Ratio - All Homes,16.000000,27.520000,32.660000,34.580000,27.480000,44.090000,11.830000,18.400000,23.430000,19.520000,...,18.850000,26.970000,14.930000,16.850000,18.660000,21.200000,26.490000,76.150000,54.770000,61.350000
Turnover - All Homes,4.077000,5.062900,5.065100,3.962000,4.531400,5.397300,4.595300,1.073300,2.964000,0.262800,...,2.658300,3.142800,5.225400,6.786300,6.443500,5.318400,4.458700,4.007000,5.609500,4.575400
Unsold Renos - All Homes,30.300000,27.000000,58.200000,35.200000,37.400000,34.300000,13.200000,300.500000,66.300000,196.600000,...,107.900000,128.100000,166.400000,108.300000,86.100000,107.800000,90.300000,92.600000,85.300000,67.400000
Zillow Home Value Index - All Homes,463781.000000,468553.000000,413467.000000,437304.000000,450374.000000,383102.000000,462955.000000,203130.000000,189892.000000,151501.000000,...,152112.000000,87927.000000,194178.000000,200900.000000,246812.000000,204702.000000,186181.000000,154284.000000,198094.000000,200362.000000
Zillow Rental Index - All Homes,2225.000000,2392.000000,2148.000000,2273.000000,2274.000000,2037.000000,2340.000000,1528.000000,1421.000000,1315.000000,...,1210.000000,958.000000,1401.000000,1433.000000,1577.000000,1494.000000,1386.000000,1251.000000,1384.000000,1397.000000

In [17]:
#Convert to csv
df2.to_csv("../data/ATLListings.csv", encoding="utf-8", index=True, header=True)